#!/bin/sh
dir=$(dirname "$(readlink -f "$0")")

# build nixpkgs
nix-build -Q ./nixpkgs -o ./nixpkgs/.nixpkgs > /dev/null

# build nixos
NIX_CFLAGS_COMPILE="-O3 -march=native -mtune=native" \
NIX_PATH="nixpkgs=./nixpkgs/.nixpkgs:nixpkgs-overlays=./nixpkgs/overlays:nixos-config=./configuration.nix" \
  nixos-rebuild "$@"
