#!/bin/sh
dir=$(dirname "$(readlink -f "$0")")

# build nixpkgs
nix-build -Q ./core -o ./core/.nixpkgs > /dev/null

# build nixos
NIX_CFLAGS_COMPILE="-O3 -march=native -mtune=native" \
NIX_PATH="nixpkgs=./core/.nixpkgs:nixpkgs-overlays=./core/overlays:nixos-config=./configuration.nix" \
  nixos-rebuild "$@"
