#!/bin/sh
dir=$(dirname "$(readlink -f "$0")")

# build nixpkgs
nix-build -Q ./pkgs -o ./pkgs/.nixpkgs > /dev/null

# build nixos
NIX_CFLAGS_COMPILE="-O3 -march=native -mtune=native" \
NIX_PATH="nixpkgs=./pkgs/.nixpkgs:nixpkgs-overlays=./pkgs/overlays:nixos-config=./configuration.nix" \
  nixos-rebuild "$@"
